In [1]:
import tensorflow as tf

In [2]:
mat = tf.constant([[11,22,33,44],[2,25,1,8],[5,7,78,12],[95,21,47,20]])
print(mat)

tf.Tensor(
[[11 22 33 44]
 [ 2 25  1  8]
 [ 5  7 78 12]
 [95 21 47 20]], shape=(4, 4), dtype=int32)


In [3]:
matmax = tf.math.reduce_max(mat,axis = 1)

In [4]:
matmax

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([44, 25, 78, 95])>

In [8]:
vtr1 = tf.constant([[2,5,1],[1,2,3],[9,7,8]])
vtr2 = tf.constant([[13,14,11],[6,3,45],[71,1,10]])
vtr3 = vtr1 + vtr2

In [9]:
vtr3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 19, 12],
       [ 7,  5, 48],
       [80,  8, 18]])>

In [10]:
vtr4 = tf.constant([[1,3],[4,45],[6,67]])
list1 = [[56,2],[34,1],[67,8]]
vtr5 = vtr4 + list1
vtr5

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[57,  5],
       [38, 46],
       [73, 75]])>